version: '3.8'

services:
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      TZ: Asia/Seoul
      WATCHTOWER_CLEANUP: 'true'
      WATCHTOWER_POLL_INTERVAL: 86400
    restart: unless-stopped
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "3000:80"
    environment:
      NODE_ENV: production
