#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Run lint-staged
npm run lint-stagedsdf

# Check if there are any changes to be committed
if [ -n "$(git status --porcelain)" ]; then
  git add .
  git commit -m "[CNG] lint apply"
fi

# Allow the push to proceed
exit 0